### ISSUE TITLE
Nuclei Scans for prototype pollution opens a chrome window, which is not always closed

### ISSUE THREAD

**Issue by blackblastie** [R-s0n/ars0n-framework#1]
While running wildfire.py --scan, it kicks off Nuclei scans. The Nuclei scans open chrome windows for each test for prototype pollution. These aren't always closed automatically by the script, so would be good to have something that checks for stranded processes and kills them.

**Comment by R-s0n** [comment]
Thanks for the heads up!!  I've noticed the same thing.  It's an issue with Nuclei, but I can definitely put some logic to force close those processes if Nuclei hangs.  I'll try to get that in ASAP!~

**Comment by R-s0n** [comment]
@blackblastie Okay, we should be good to go!  I've completely refactored the Fire-Scanner modules into a new script that runs several granular Nuclei scans based on what I've had success with in the past.  I still have a lot of work to improve the scanning, but I've put a control specifically in place to fix the open chromium windows.  Please let me know if I've missed any edge-cases, otherwise best of luck!!
