### ISSUE TITLE
How do we actually start the scanning process?

### ISSUE THREAD

**Issue by VainXploits** [R-s0n/ars0n-framework#32]
![image](https://github.com/R-s0n/ars0n-framework/assets/133690846/d5ceb6ff-a5e6-498a-82fa-589bfd0ea699)

so, I did run the wildfire command and when I refresh the page, the scan status is still "NOT Running"...

**Comment by R-s0n** [comment]
I'm guessing there's something wrong with the toolkit service since everything else seems to be running fine.  Are you running this on a clean version of Kali 2023.3?  If not, check to make sure nothing else was already running on port 5000.  The framework needs port 3000 for the client, 8000 for the API, and 5000 for the toolkit service.  I plan to make those controllable in the near future but I'm a bit of ways away.

**Comment by R-s0n** [comment]
I've set up a discord with a troubleshooting channel.  Let's take this conversation there since this is not yet known to be an issue with the tool itself.  If we do find that this is caused by a bug in the software, I will re-open this and move forward as necessary.

https://discord.gg/dDe4hmk4qs
