### ISSUE TITLE
After Installing the FQDN button not working

### ISSUE THREAD

**Issue by 9MaDdy16** [R-s0n/ars0n-framework#5]
After Installing It directly shows the FQDN button and it not working . 

![Issu](https://user-images.githubusercontent.com/108828207/222366118-04bea4fc-9067-4f90-85c3-5a7a15b483dc.png)

![issue 2](https://user-images.githubusercontent.com/108828207/222371806-3dd0cc49-5150-42a6-a750-7f3bfa39733f.png)

I tried installing again but it gives the same issue it show FQDN button and after clicking it doesn't work.

**Comment by R-s0n** [comment]
Ah, your MongoDB service has not started.  I've seen this with a few other users today and in both cases the issue was their processor.  Can you please confirm that the machine you are using meets the minimum requirements for MongoDB?  If it does, then you might be using an older version of Kali that fails trying to run `apt-get install mongodb`.  You can always download the MongoDB binary for Debian 11 and just run it manually.  Either way, we need to get mongo running so the server can connect.

**Comment by 9MaDdy16** [comment]
Installing and starting Mongodb manually worked. Thank you for the help.
