### ISSUE TITLE
Can't Add FQDN

### ISSUE THREAD

**Issue by Lesrad** [R-s0n/ars0n-framework#6]
![image](https://user-images.githubusercontent.com/7493934/222732777-d0126366-7e5c-45bd-a4b1-625ff070f6cc.png)
I just can't get the Add FQDN to add anything, in your video it pops up in a new page, mine responds exactly like in the SS, the button never responds :)

**Comment by Lesrad** [comment]
It did work on a fresh kali install though :)
Ty

**Comment by R-s0n** [comment]
The issue is your  MongoDB instance isn't running currently.  Sounds like the MongoDB install didn't work on your first install, did work on the second install (fresh Kali), but the service is not starting after a reboot.  

`service mongod start` should fix the problem if I'm correct.  Either way, you'll need to get MongoDB running before you start the server so it can make the connection.

**Comment by blackblastie** [comment]
I was actually having this problem and confirmed your solution fixes it, minus the small typo in the service name of `mongodb` :)

**Comment by blackblastie** [comment]
I could do a quick PR to add that command to `run.sh` so that we know mongo is up when trying to start, would that help?

**Comment by Lesrad** [comment]
Perfect works now, thanks

**Comment by KalingGo** [comment]
it worked with me when i used this command:
$ sudo systemctl enable mongodb
$ sudo systemctl start mongodb

**Comment by R-s0n** [comment]
Thanks for the help, everyone!  Sounds like I definitely need to get some more logic around Mongo.  There has been a lot of issues with installing it.  I'll take a look, this weekend, and see if I can add some try/catches.

And @blackblastie feel free to submit any PR you'd like!!  And thanks for getting my squared away on the typo ;)

**Comment by R-s0n** [comment]
I've updated the `run.sh` script and added a debug script.  Hopefully that will mitigate a bit of these issues.

**Comment by Lesrad** [comment]
Some extra issues, the below are not being created automatically. I manually added them.
sudo apt install htmlmin  
/tmp/sublist3r.tmp
/tmp/subdomainizer.tmp

**Comment by R-s0n** [comment]
Oh interesting!!  The Sublist3r stack trace is expected.  That just means the tool didn't find anything.  I need to clean up the stdout so it looks better.  The SubDomainizer stack trace is definitely a bug, though.  Not sure why that package isn't being picked up with the install script.  I'll get that added today.

**Comment by R-s0n** [comment]
I've got an update on the issues you're seeing, here, @Lesrad.  There are some major changes to how `pip` works in Kali.   They're trying to force you to use `apt-get` instead of `pip` to install Python packages but installing them through `apt-get` is super janky.  

Here's a blog post with a terribly complicated way to fix it: https://technicalnavigator.in/how-to-fix-error-externally-managed-environment-in-python-kali-linux/

I'm working on updating the install script to compensate for this but they aren't making it easy.  I don't know what OffSec was thinking with this one.  Why does everyone have to try and fix things that aren't broken...

**Comment by R-s0n** [comment]
Okay, we should be squared away!  I just pushed up a major update to the install and fire-starter scripts.  These updates fix the pip issues with the install script and makes the Fire Starter module *much* cleaner. I've tested this on the most recent version of Kali, along with the previous two.  These tests were done twice, first on Virtualbox 6.1 and next on Virtualbox 7.  Hopefully this covers all the bases, haha.  Thanks again for all the help, everyone!!
